# Generated by Django 6.0.7 on 2026-08-06 05:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_department_order_index'),
        ('employees', '0003_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField(blank=True, help_text='Số tiền đề xuất (VNĐ)', null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='companies.company')),
                ('decided_by', models.ForeignKey(blank=True, db_column='decided_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_proposals', to='employees.employee')),
                ('requester', models.ForeignKey(db_column='requester_id', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='employees.employee')),
            ],
            options={
                'db_table': 'proposals',
                'ordering': ['-created_at'],
            },
        ),
    ]
