# Generated by Django 6.0.7 on 2026-07-24 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_company_id_alter_department_id'),
        ('employees', '0002_alter_employee_id_alter_employeecompany_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='companies.company')),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('meeting', 'Cuộc họp'), ('personal', 'Lịch cá nhân'), ('reminder', 'Nhắc nhở')], default='meeting', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('online_meeting_link', models.CharField(blank=True, max_length=500, null=True)),
                ('need_pickup_car', models.BooleanField(default=False)),
                ('has_gift', models.BooleanField(default=False)),
                ('gift_note', models.TextField(blank=True, null=True)),
                ('invite_all_company', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to='employees.employee')),
                ('driver', models.ForeignKey(blank=True, db_column='driver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.driver')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventAttachment',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('file_url', models.CharField(max_length=500)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='events.event')),
            ],
            options={
                'db_table': 'event_attachments',
            },
        ),
        migrations.CreateModel(
            name='EventDepartmentInvite',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='event_invites', to='companies.department')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='department_invites', to='events.event')),
            ],
            options={
                'db_table': 'event_department_invites',
            },
        ),
        migrations.CreateModel(
            name='EventEmployeeInvite',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='event_invites', to='employees.employee')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='employee_invites', to='events.event')),
            ],
            options={
                'db_table': 'event_employee_invites',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('meeting_invite', 'Mời họp'), ('upcoming_meeting', 'Sắp diễn ra cuộc họp'), ('task_completed', 'Hoàn thành công việc'), ('work_report', 'Báo cáo công việc'), ('promotion', 'Thăng chức'), ('approval_pending', 'Chờ duyệt'), ('overdue_task', 'Công việc quá hạn'), ('general', 'Thông báo chung')], max_length=50)),
                ('icon_key', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('link_url', models.CharField(blank=True, max_length=500, null=True)),
                ('related_table', models.CharField(blank=True, max_length=100, null=True)),
                ('related_id', models.CharField(blank=True, max_length=36, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.company')),
                ('recipient', models.ForeignKey(db_column='recipient_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employees.employee')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
