# Generated by Django 6.0.7 on 2026-07-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_id_alter_employeecompany_id_and_more'),
        ('events', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='source_audit_log',
            field=models.ForeignKey(blank=True, db_column='source_audit_log_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='integrations.auditlog'),
        ),
        migrations.AddField(
            model_name='notification',
            name='triggered_by',
            field=models.ForeignKey(blank=True, db_column='triggered_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to='employees.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='eventdepartmentinvite',
            unique_together={('event', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='eventemployeeinvite',
            unique_together={('event', 'employee')},
        ),
    ]
