"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-_hx_qy)u6nnz2b(vt^w*afou#42bi4dgo@ir%b2+^jk0-miu__')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 't')

# ALLOWED_HOSTS mặc định '*' (dev). Khi deploy, set biến môi trường ALLOWED_HOSTS
# (phân tách bằng dấu phẩy) để giới hạn đúng domain thật.
_allowed_hosts_env = os.getenv('ALLOWED_HOSTS')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()] if _allowed_hosts_env else ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'corsheaders',
    # Local apps
    'companies',
    'projects',
    'tasks',
    'employees',
    'integrations.apps.IntegrationsConfig',
    'events',
    'meetings',
]

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

CELERY_BEAT_SCHEDULE = {
    'generate-time-based-notifications-every-15-min': {
        'task': 'events.tasks.generate_time_based_notifications',
        'schedule': 900.0,  # 15 minutes
    },
}

# MinIO / S3-compatible storage configuration (MinIO tự host, Cloudflare R2, AWS S3, ...)
MINIO_ENDPOINT = os.getenv('MINIO_ENDPOINT', 'localhost:9000')
MINIO_ACCESS_KEY = os.getenv('MINIO_ACCESS_KEY', 'minioadmin')
MINIO_SECRET_KEY = os.getenv('MINIO_SECRET_KEY', 'minioadmin')
MINIO_BUCKET_NAME = os.getenv('MINIO_BUCKET_NAME', 'vela-attachments')
MINIO_USE_SSL = os.getenv('MINIO_USE_SSL', 'False').lower() in ('true', '1', 't')
# Region ký request S3. R2 bắt buộc phải là 'auto'; MinIO tự host/AWS S3 để trống.
MINIO_REGION = os.getenv('MINIO_REGION') or None
# URL public để trả về cho client (r2.dev subdomain hoặc custom domain).
# Khác với MinIO tự host, R2 KHÔNG chèn tên bucket vào path public — khi set biến
# này thì URL sẽ là "{MINIO_PUBLIC_URL_BASE}/{object_name}" (không có bucket_name).
MINIO_PUBLIC_URL_BASE = os.getenv('MINIO_PUBLIC_URL_BASE') or None


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS_ALLOWED_ORIGINS mặc định là các origin dev local. Khi deploy, set biến môi
# trường CORS_ALLOWED_ORIGINS (phân tách bằng dấu phẩy) để trỏ đúng domain frontend thật.
_cors_origins_env = os.getenv('CORS_ALLOWED_ORIGINS')
CORS_ALLOWED_ORIGINS = (
    [o.strip() for o in _cors_origins_env.split(',') if o.strip()]
    if _cors_origins_env
    else [
        "http://localhost:3000",
        "http://localhost:5173",
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
    ]
)

from corsheaders.defaults import default_headers

# "authorization" đã nằm sẵn trong default_headers của corsheaders — không cần
# thêm header tự chế nào nữa (X-Employee-Id đã bị xóa bỏ, thay bằng JWT Bearer).
CORS_ALLOW_HEADERS = list(default_headers)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'employees.authentication.TrackingJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_db_host = os.getenv('DB_HOST', 'localhost')
_db_options = {'charset': 'utf8mb4'}

# Chỉ bật SSL khi trỏ tới DB thật ở xa (Aiven...) — MySQL local (localhost/127.0.0.1)
# thường không bật SSL nên ép ssl ở đây sẽ làm hỏng kết nối dev.
if _db_host not in ('localhost', '127.0.0.1'):
    _db_options['ssl'] = {'ca': str(BASE_DIR / 'config' / 'certs' / 'aiven-ca.pem')}

if os.getenv('DATABASE_URL'):
    # Render/Aiven đôi khi cấp sẵn 1 connection string dạng mysql://user:pass@host:port/db
    DATABASES = {
        'default': {
            **dj_database_url.parse(os.getenv('DATABASE_URL')),
            'OPTIONS': _db_options,
            'CONN_MAX_AGE': 60,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'project_management'),
            'USER': os.getenv('DB_USER', 'root'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'your_password'),
            'HOST': _db_host,
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': _db_options,
            # Tái sử dụng connection — quan trọng vì Aiven free giới hạn số connection đồng thời.
            'CONN_MAX_AGE': 60,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Google Drive Integration Settings
_creds_path = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
if _creds_path and not os.path.isabs(_creds_path):
    GOOGLE_APPLICATION_CREDENTIALS = str(BASE_DIR / _creds_path)
else:
    GOOGLE_APPLICATION_CREDENTIALS = _creds_path

GOOGLE_DRIVE_ROOT_FOLDER_ID = os.getenv("GOOGLE_DRIVE_ROOT_FOLDER_ID")


