# Generated by Django 6.0.7 on 2026-07-23 06:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('drive_folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('drive_folder_url', models.CharField(blank=True, max_length=500, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.company')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
