# Generated by Django 6.0.7 on 2026-07-31 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_id_alter_department_id'),
        ('employees', '0003_employee_user'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAISetting',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('claude_api_key_encrypted', models.TextField(blank=True, null=True)),
                ('is_ai_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='ai_setting', to='companies.company')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
            ],
            options={
                'db_table': 'company_ai_settings',
            },
        ),
    ]
