# Generated by Django 6.0.7 on 2026-07-31 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_companyaisetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyaisetting',
            old_name='claude_api_key_encrypted',
            new_name='gemini_api_key_encrypted',
        ),
    ]
