# Generated by Django 6.0.7 on 2026-07-31 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_rename_claude_api_key_encrypted_companyaisetting_gemini_api_key_encrypted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyaisetting',
            old_name='gemini_api_key_encrypted',
            new_name='api_key_encrypted',
        ),
    ]
