# Generated by Django 6.0.7 on 2026-08-07 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_department_order_index'),
        ('integrations', '0004_rename_gemini_api_key_encrypted_companyaisetting_api_key_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='companies.company'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.CharField(blank=True, help_text='Câu mô tả tiếng Việt sẵn để hiển thị (vd "tạo việc: Giao cho @lan"), tạo sẵn lúc ghi log để khỏi phải tra lại record gốc (có thể đã bị xoá).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login')], max_length=10),
        ),
    ]
