# Generated by Django 6.0.7 on 2026-08-27 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeecompany_can_approve_proposals'),
        ('integrations', '0006_fix_action_column_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('service_account_json_encrypted', models.TextField(blank=True, null=True)),
                ('connected_account_email', models.CharField(blank=True, max_length=255, null=True)),
                ('root_folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('root_folder_url', models.CharField(blank=True, max_length=500, null=True)),
                ('apps_script_url', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
            ],
            options={
                'db_table': 'google_drive_config',
            },
        ),
    ]
