# Generated by Django 6.0.7 on 2026-08-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeecompany_can_approve_proposals'),
        ('tasks', '0004_backfill_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='effort_points',
            field=models.IntegerField(blank=True, choices=[(1, 'Nhỏ'), (3, 'Vừa'), (5, 'Lớn'), (8, 'Rất lớn')], null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_milestone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='pic',
            field=models.ForeignKey(blank=True, db_column='pic_id', help_text='Người phụ trách chính (khác task_assignments — có thể nhiều người tham gia)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pic_tasks', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Ý tưởng', 'Ý tưởng'), ('Cần làm', 'Cần làm'), ('Đang làm', 'Đang làm'), ('Hoàn thành', 'Hoàn thành')], default='Cần làm', max_length=50),
        ),
    ]
