# Generated by Django 6.0.7 on 2026-08-15 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_department_order_index'),
        ('tasks', '0006_remap_trehan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(blank=True, db_column='department_id', help_text='Phòng ban phụ trách — gán trực tiếp, không còn suy ra qua người được gán việc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='companies.department'),
        ),
    ]
