# Generated by Django 6.0.7 on 2026-08-15 08:48

from django.db import migrations


def backfill_task_department(apps, schema_editor):
    """department vừa được thêm là cột suy ra 1 lần từ dữ liệu gán việc cũ —
    lặp lại đúng logic từng dùng để hiển thị/sort cột "Bộ phận" trước khi có
    cột này (assignment đầu tiên theo id, ưu tiên phòng is_primary), để không
    đổi giá trị đang hiển thị cho người dùng. Từ migration này trở đi,
    department là field độc lập, chỉnh qua API chứ không tự suy ra nữa."""
    Task = apps.get_model('tasks', 'Task')
    TaskAssignment = apps.get_model('tasks', 'TaskAssignment')
    EmployeeDepartment = apps.get_model('employees', 'EmployeeDepartment')

    for task in Task.objects.filter(department__isnull=True):
        assignment = TaskAssignment.objects.filter(task_id=task.id).order_by('id').first()
        if not assignment:
            continue
        dept_link = EmployeeDepartment.objects.filter(
            employee_id=assignment.employee_id
        ).order_by('-is_primary', 'id').first()
        if dept_link:
            task.department_id = dept_link.department_id
            task.save(update_fields=['department'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_department'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_task_department, noop),
    ]
