# Generated by Django 6.0.7 on 2026-08-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_drive_file_id_task_drive_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='can_automate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_problem',
            field=models.BooleanField(default=False),
        ),
    ]
