# Generated by Django 6.0.7 on 2026-09-04 08:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_company_due_soon_days'),
        ('employees', '0007_employeecompany_allowance_and_more'),
        ('projects', '0003_project_department_project_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_role', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('lead', 'Tiềm năng'), ('active', 'Đang làm việc'), ('closed', 'Đã chốt'), ('lost', 'Ngừng')], default='lead', max_length=10)),
                ('contract_info', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('stage_rnd', models.CharField(choices=[('pending', 'Chưa'), ('doing', 'Đang làm'), ('done', 'Đã chốt')], default='pending', max_length=10)),
                ('stage_define', models.CharField(choices=[('pending', 'Chưa'), ('doing', 'Đang làm'), ('done', 'Đã chốt')], default='pending', max_length=10)),
                ('stage_suggest', models.CharField(choices=[('pending', 'Chưa'), ('doing', 'Đang làm'), ('done', 'Đã chốt')], default='pending', max_length=10)),
                ('stage_solution', models.CharField(choices=[('pending', 'Chưa'), ('doing', 'Đang làm'), ('done', 'Đã chốt')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='companies.company')),
                ('linked_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_clients', to='projects.project')),
                ('owner', models.ForeignKey(blank=True, help_text='Người follow khách hàng này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followed_clients', to='employees.employee')),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientComment',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clients.client')),
            ],
            options={
                'db_table': 'client_comments',
                'ordering': ['created_at'],
            },
        ),
    ]
