# Generated by Django 6.0.7 on 2026-08-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_id_alter_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
    ]
