# Generated by Django 6.0.7 on 2026-08-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_department_order_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='drive_folder_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
