# Generated by Django 6.0.7 on 2026-08-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_department_drive_folder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='due_soon_days',
            field=models.IntegerField(default=2, help_text='Số ngày trước hạn để hiện cảnh báo "Sắp đến hạn" (màu vàng) cho việc chưa xong'),
        ),
    ]
