# Generated by Django 6.0.7 on 2026-08-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
