# Generated by Django 6.0.7 on 2026-07-23 06:19

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar_url', models.CharField(blank=True, max_length=500, null=True)),
                ('position_title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_in_company', models.CharField(blank=True, max_length=100, null=True)),
                ('joined_at', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('left_at', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='company_employees', to='companies.company')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='employee_companies', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'Employee Companies',
                'db_table': 'employee_companies',
                'unique_together': {('employee', 'company')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('joined_at', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('left_at', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='department_employees', to='companies.department')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='employee_departments', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'Employee Departments',
                'db_table': 'employee_departments',
                'unique_together': {('employee', 'department')},
            },
        ),
    ]
