# Generated by Django 6.0.7 on 2026-08-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompany',
            name='can_approve_proposals',
            field=models.BooleanField(default=False, help_text='Được quyền Duyệt/Từ chối đề xuất chi phí trong công ty này'),
        ),
    ]
