# Generated by Django 6.0.7 on 2026-09-04 04:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Tài khoản tự đăng ký (xem employees.auth_views.register_view) tạo ra ở trạng thái chưa duyệt (False) và không đăng nhập được cho tới khi người có quyền duyệt trong trang Nhân sự → Chờ duyệt. Nhân viên tạo qua admin/seed mặc định coi như đã duyệt.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='zalo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeReaction',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_employee', models.ForeignKey(db_column='from_employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='reactions_given', to='employees.employee')),
                ('to_employee', models.ForeignKey(db_column='to_employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='reactions_received', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_reactions',
                'unique_together': {('from_employee', 'to_employee')},
            },
        ),
    ]
