# Generated by Django 6.0.7 on 2026-09-04 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_due_soon_days'),
        ('employees', '0006_employee_is_approved_employee_zalo_employeereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompany',
            name='allowance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeecompany',
            name='base_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeecompany',
            name='current_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PointsFormulaConfig',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('points_per_effort_unit', models.IntegerField(default=3, help_text='Điểm cho mỗi đơn vị độ khó (Task.effort_points)')),
                ('on_time_bonus', models.IntegerField(default=5, help_text='Thưởng điểm mỗi việc hoàn thành đúng hạn')),
                ('auto_apply_salary', models.BooleanField(default=True, help_text='Lên Level tự động áp lương cứng + phụ cấp của bậc mới')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_formula', to='companies.company')),
            ],
            options={
                'db_table': 'points_formula_configs',
            },
        ),
        migrations.CreateModel(
            name='LevelTier',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('min_points', models.IntegerField(default=0)),
                ('base_salary', models.IntegerField(default=0)),
                ('allowance', models.IntegerField(default=0)),
                ('benefits', models.CharField(blank=True, default='', max_length=255)),
                ('order_index', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_tiers', to='companies.company')),
            ],
            options={
                'db_table': 'level_tiers',
                'ordering': ['order_index', 'level'],
                'unique_together': {('company', 'level')},
            },
        ),
    ]
