# Generated by Django 6.0.7 on 2026-09-04 08:06

import django.db.models.deletion
import recruitment.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_company_due_soon_days'),
        ('employees', '0007_employeecompany_allowance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(blank=True, default='', max_length=100)),
                ('requirements_note', models.TextField(blank=True, default='')),
                ('jd', models.TextField(blank=True, default='')),
                ('channels', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Đang tuyển'), ('closed', 'Đã đóng')], default='open', max_length=10)),
                ('public_token', models.CharField(default=recruitment.models._short_token, editable=False, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='companies.department')),
            ],
            options={
                'db_table': 'job_postings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('cv_file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('cv_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_letter', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='Link công khai', max_length=100)),
                ('stage', models.CharField(choices=[('applied', 'Mới nộp'), ('screening', 'Sàng lọc'), ('interview', 'Phỏng vấn'), ('offer', 'Đề nghị'), ('hired', 'Đã tuyển'), ('rejected', 'Từ chối')], default='applied', max_length=10)),
                ('interview_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.jobposting')),
            ],
            options={
                'db_table': 'candidates',
                'ordering': ['-created_at'],
            },
        ),
    ]
